language: node_js
node_js:
  - "9"
addons:
  apt:
    update: true
services:
  - mysql
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password'; FLUSH PRIVILEGES;"
  - sudo mysql_upgrade --force
  - sudo service mysql restart
  - mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS smallmenu DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_general_ci;"
  - mysql -uroot -proot -e "use mysql; SELECT host, user, authentication_string FROM user;"
  - mysql -uroot -proot -e "show databases; SELECT host, user, authentication_string FROM mysql.user;"
  - mysql -uroot -proot -e "GRANT ALL PRIVILEGES ON smallmenu.* TO 'root'@'%';";
install:
  - npm install
script:
  - npm start