language: node_js
node_js:
  - "9"
addons:
  apt:
    update: true
services:
  - mysql
before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS smallmenu DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_general_ci;"
install:
  - npm install
script:
  - npm test