language: node_js
node_js:
  - "9"
services:
  - mysql
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO root@localhost IDENTIFIED BY 'root';"
  - sudo service mysql restart
  - sudo mysql -e "FLUSH PRIVILEGES;"
  - mysql -e 'CREATE DATABASE IF NOT EXISTS smallmenu DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_general_ci;'
install:
  - npm install
script:
  - npm start