version: "3"
services:
  mysql:
    image: "mysql:5"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: "smallmenu"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  web:
    build: .
    links:
      - mysql
    ports:
      - "3000:3000"
    depends_on:
      - "mysql"
    volumes:
      - .:/code
    command: ["./wait-for-it.sh", "mysql:3306", "--", "npm", "start"]